# Generated by Django 2.2.7 on 2020-10-30 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voterlist',
            fields=[
                ('Voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
                ('Phone', models.CharField(max_length=14)),
                ('Date_of_Birth', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=300)),
                ('Gender', models.CharField(max_length=6)),
                ('Province', models.CharField(max_length=50)),
                ('Citizen_ID_Number', models.CharField(max_length=50)),
                ('Voter_ID_Number', models.CharField(max_length=20)),
                ('Photo_Candidate', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('Photo_Citizenship_Front', models.ImageField(upload_to='ctzn_frnt')),
                ('Photo_Citizenship_Rare', models.ImageField(upload_to='ctzn_rer')),
                ('Remark', models.CharField(default='Pending', max_length=10)),
                ('Vote_Status', models.CharField(default='None', max_length=10)),
            ],
        ),
    ]
